services:
  - type: web
    name: familia-shilo-backend
    env: node
    plan: free
    runtime: node
    buildCommand: ./render-build.sh
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NPM_CONFIG_PRODUCTION
        value: true
      - key: DISABLE_NEXTJS
        value: true
      - key: BUILD_TOOL
        value: none 